import { readFileSync } from 'node:fs';

/**
 * `*_FILE` secret delivery.
 *
 * A container's environment is persisted in its config on disk and printed by
 * `docker inspect`; an env file is a plaintext copy of every credential. So a
 * secret reaches the process as a FILE on tmpfs (materialized from the
 * encrypted host store by deploy/swift-secrets) and the process reads it into
 * its own memory here, before any configuration is validated:
 *
 *   NAME_FILE=/run/secrets/NAME  →  NAME=<file content, one trailing newline stripped>
 *
 * Rules, each pinned by src/__tests__/secret-files.test.ts:
 *   - only the names below are honoured, so an env variable can never turn
 *     this into a read of an arbitrary file;
 *   - NAME and NAME_FILE both set is a refusal — a secret comes from exactly
 *     one place, never "whichever wins";
 *   - a file that is missing, unreadable or empty is a refusal, never a
 *     silent fallback;
 *   - no value is ever logged. Messages name the variable and the path.
 *
 * ../boot/secret-files.ts applies this to process.env as the FIRST import of
 * every entrypoint (server, worker, migrate).
 */
export const SECRET_FILE_NAMES = [
  // Database: the whole URL, or the password to assemble one from POSTGRES_*
  // parts (assembleDatabaseUrl below).
  'DATABASE_URL',
  'POSTGRES_PASSWORD',
  // Application authority (generated by deploy/gen-secrets.sh).
  'JWT_SECRET',
  'OTP_HASH_SECRET',
  'MASTER_KEK',
  'STORAGE_SIGNING_SECRET',
  'STORAGE_SIGNING_SECRET_PREVIOUS',
  'CONSENT_IP_PEPPER',
  // Search.
  'MEILISEARCH_KEY',
  // Notifications.
  'TWILIO_API_KEY_SECRET',
  'SMTP_PASS',
  // MMG mobile money.
  'MMG_API_KEY',
  'MMG_PASSWORD',
  'MMG_MKEY',
  'MMG_MSECRET',
  // Card rails.
  'PAYMENT_GATEWAY_KEY',
  'PAYMENT_GATEWAY_SECRET',
  'STRIPE_SECRET_KEY',
  // Object storage (documents, and the backup bucket).
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  // Ops plane and operator tokens (the first three are generated by
  // deploy/gen-secrets.sh; the bootstrap password is chosen by the operator).
  'TEST_CONTROL_SECRET',
  'METRICS_TOKEN',
  'HEALTH_DETAIL_TOKEN',
  'SWIFT_BOOTSTRAP_PASSWORD',
  // The key both halves of a two-person seed or promotion approval are signed
  // with (seed-plan.ts). Only the one-off seed ceremony container reads it.
  'SEED_PLAN_SECRET',
  // Keyed hashes and signatures: the salts and the ads token secret are
  // required in production and generated; the cursor and velocity secrets
  // fall back to the session secret and may be delivered separately.
  'ATTRIB_SALT',
  'IDENTITY_SALT',
  'SCAN_IP_SALT',
  'ADS_EVENT_SECRET',
  'SERVICE_PROVIDER_CURSOR_SECRET',
  'VELOCITY_KEY_SECRET',
  // Inbound webhook and third-party keys.
  'AGENT_CASH_WEBHOOK_SECRET',
  'GOOGLE_MAPS_API_KEY_BACKEND',
  'SENTRY_DSN',
  // URLs that carry a credential. The RLS-bypass login URL is the most
  // privileged database credential there is (dormant until the
  // least-privilege login exists); a Redis URL may carry a password (the
  // pilot's does not, and Compose sets that credential-free endpoint
  // plainly); an outbound alert webhook carries its token in the path.
  'SYSTEM_DATABASE_URL',
  'REDIS_URL',
  'CW_ALERT_WEBHOOK_URL',
] as const;

export type SecretFileName = (typeof SECRET_FILE_NAMES)[number];

type Env = Record<string, string | undefined>;

/** Injectable for tests; the default is the real filesystem. */
export interface SecretFileReader {
  readFileSync(path: string): Buffer;
}

const realFiles: SecretFileReader = { readFileSync: (path) => readFileSync(path) };

const isSet = (value: string | undefined): value is string => value !== undefined && value !== '';

/**
 * Loads every allowlisted NAME_FILE into NAME on `env`, removing NAME_FILE so
 * a second pass is a no-op. Returns the names loaded. Throws on the first
 * refusal with a message that carries no value.
 */
export function applySecretFiles(env: Env, files: SecretFileReader = realFiles): SecretFileName[] {
  const loaded: SecretFileName[] = [];
  for (const name of SECRET_FILE_NAMES) {
    const fileVar = `${name}_FILE`;
    const path = env[fileVar];
    if (!isSet(path)) continue;
    if (isSet(env[name])) {
      throw new Error(`FATAL: ${name} and ${fileVar} are both set — a secret must come from exactly one place. Refusing to start.`);
    }
    let raw: Buffer;
    try {
      raw = files.readFileSync(path);
    } catch (error) {
      const code = (error as { code?: string }).code ?? 'unreadable';
      throw new Error(`FATAL: ${fileVar} points at ${path}, which could not be read (${code}). Refusing to start.`);
    }
    let value = raw.toString('utf8');
    if (value.endsWith('\n')) value = value.slice(0, value.endsWith('\r\n') ? -2 : -1);
    if (value === '') {
      throw new Error(`FATAL: ${fileVar} points at ${path}, which is empty. Refusing to start.`);
    }
    env[name] = value;
    delete env[fileVar];
    loaded.push(name);
  }
  return loaded;
}

const HOST = /^[A-Za-z0-9][A-Za-z0-9.-]*$/;
const PORT = /^[0-9]{1,5}$/;

/**
 * The database credential from parts. Prisma wants one URL, and a URL with the
 * password inside it cannot be a container environment value (see above), so
 * the deploy passes POSTGRES_HOST/PORT/USER/DB in the clear and the password
 * as a file; this assembles DATABASE_URL in memory, percent-encoding every
 * component so no character in a password can break the URL.
 *
 * Returns true when it assembled the URL, false when there was nothing to do.
 * Refuses when DATABASE_URL and POSTGRES_PASSWORD are both present: one place.
 */
export function assembleDatabaseUrl(env: Env): boolean {
  const password = env['POSTGRES_PASSWORD'];
  if (isSet(env['DATABASE_URL']) && isSet(password)) {
    throw new Error('FATAL: DATABASE_URL and POSTGRES_PASSWORD are both set — the database credential must come from exactly one place (a URL, or POSTGRES_* parts with the password file). Refusing to start.');
  }
  if (!isSet(password)) return false;
  const host = env['POSTGRES_HOST'];
  const user = env['POSTGRES_USER'];
  const database = env['POSTGRES_DB'];
  const port = isSet(env['POSTGRES_PORT']) ? env['POSTGRES_PORT'] : '5432';
  for (const [part, value] of [['POSTGRES_HOST', host], ['POSTGRES_USER', user], ['POSTGRES_DB', database]] as const) {
    if (!isSet(value)) {
      throw new Error(`FATAL: POSTGRES_PASSWORD is set but ${part} is not — the database URL cannot be assembled. Refusing to start.`);
    }
  }
  if (!HOST.test(host as string)) {
    throw new Error('FATAL: POSTGRES_HOST must be a plain hostname or address. Refusing to start.');
  }
  if (!PORT.test(port)) {
    throw new Error('FATAL: POSTGRES_PORT must be a port number. Refusing to start.');
  }
  env['DATABASE_URL'] = `postgresql://${encodeURIComponent(user as string)}:${encodeURIComponent(password)}@${host}:${port}/${encodeURIComponent(database as string)}`;
  return true;
}
