import { describe, it, expect, beforeAll } from 'vitest';
import {
  constants,
  createHash,
  generateKeyPair,
  privateDecrypt,
  publicEncrypt,
  randomBytes,
  type KeyObject,
} from 'node:crypto';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fromMajor, fromMinor } from '../utils/currency-amount';
import { applySecretFiles } from '../utils/secret-files';
import {
  MMG_CHECKOUT_PRODUCT_DESCRIPTION,
  MMG_CHECKOUT_SANDBOX_URL,
  MMG_CHECKOUT_UAT_URL,
  MmgCheckoutError,
  SandboxMmgCheckoutProvider,
  assertMmgCheckoutConfig,
  buildCheckoutRequest,
  buildCheckoutUrl,
  checkoutPageUrl,
  decodeCheckoutToken,
  decryptCheckoutResultToken,
  describeShape,
  encryptCheckoutRequest,
  formatCheckoutAmount,
  getMmgCheckoutProvider,
  loadMmgCheckoutConfig,
  newMerchantTransactionId,
  oaepSha256MaxPlaintextBytes,
  requestInitiationTime,
  serializeCheckoutRequest,
  toCheckoutToken,
  type MmgCheckoutRequest,
} from '../providers/mmg/mmg-checkout';

// ---------------------------------------------------------------------------
// The MMG hosted checkout, built to the MMG UAT package (the Checkout Flow
// demo): json.dumps(indent=4) with ensure_ascii, ISO-8859-1, RSA-OAEP with
// SHA-256 and MGF1-SHA-256 and no label, base64url with the '=' KEPT, and the
// URL <page>?token=…&merchantId=…&X-Client-ID=…. Replies: base64url with the
// padding optional → the same OAEP → strict UTF-8 → a JSON object whose field
// names are still UNCONFIRMED, so only its shape is ever described.
//
// Every key here is generated by this file. No value from any MMG file.
// ---------------------------------------------------------------------------

type Pair = { publicKey: KeyObject; privateKey: KeyObject };
const rsaPair = (bits: number) => new Promise<Pair>((resolve, reject) => {
  generateKeyPair('rsa', { modulusLength: bits }, (err, publicKey, privateKey) => (err ? reject(err) : resolve({ publicKey, privateKey })));
});
const pem = (key: KeyObject) => key.export(key.type === 'private' ? { type: 'pkcs8', format: 'pem' } : { type: 'spki', format: 'pem' }).toString();

/** mmg: the pair requests are encrypted to. swift: the pair replies are
 *  encrypted to. Distinct on purpose, so a key mix-up cannot pass. */
let mmg: Pair;
let swift: Pair;
let stranger: Pair;
let small: Pair; // 2048-bit: k - 66 = 190
let weak: Pair; // 1024-bit: below the floor

beforeAll(async () => {
  [mmg, swift, stranger, small, weak] = await Promise.all([rsaPair(4096), rsaPair(4096), rsaPair(4096), rsaPair(2048), rsaPair(1024)]);
}, 120_000);

// -- An independent RSA-OAEP, written from RFC 8017 -----------------------------
// Agreement between Node and this code is interop evidence, not a tautology:
// it shares nothing with Node's OAEP but the raw RSA primitive.

type Hash = 'sha256' | 'sha1';
const hashLength = (hash: Hash) => createHash(hash).digest().length;
const xor = (a: Buffer, b: Buffer) => Buffer.from(a.map((byte, i) => byte ^ (b[i] as number)));

/** RFC 8017 B.2.1 — MGF1. */
function mgf1(hash: Hash, seed: Buffer, length: number): Buffer {
  const blocks: Buffer[] = [];
  for (let counter = 0; blocks.length * hashLength(hash) < length; counter += 1) {
    const c = Buffer.alloc(4);
    c.writeUInt32BE(counter);
    blocks.push(createHash(hash).update(seed).update(c).digest());
  }
  return Buffer.concat(blocks).subarray(0, length);
}

/** RFC 8017 §7.1.1 step 2 — EME-OAEP encoding with the empty label. */
function emeOaepEncode(message: Buffer, k: number, hash: Hash, mgfHash: Hash = hash): Buffer {
  const hLen = hashLength(hash);
  if (message.length > k - 2 * hLen - 2) throw new Error('message too long');
  const lHash = createHash(hash).update(Buffer.alloc(0)).digest();
  const db = Buffer.concat([lHash, Buffer.alloc(k - message.length - 2 * hLen - 2), Buffer.from([0x01]), message]);
  const seed = randomBytes(hLen);
  const maskedDb = xor(db, mgf1(mgfHash, seed, k - hLen - 1));
  const maskedSeed = xor(seed, mgf1(mgfHash, maskedDb, hLen));
  return Buffer.concat([Buffer.from([0x00]), maskedSeed, maskedDb]);
}

/** RFC 8017 §7.1.2 step 3 — EME-OAEP decoding with the empty label. */
function emeOaepDecode(em: Buffer, hash: Hash, mgfHash: Hash = hash): Buffer {
  const hLen = hashLength(hash);
  const maskedSeed = em.subarray(1, 1 + hLen);
  const maskedDb = em.subarray(1 + hLen);
  const seed = xor(maskedSeed, mgf1(mgfHash, maskedDb, hLen));
  const db = xor(maskedDb, mgf1(mgfHash, seed, em.length - hLen - 1));
  const lHash = createHash(hash).update(Buffer.alloc(0)).digest();
  let i = hLen;
  while (i < db.length && db[i] === 0x00) i += 1;
  if (em[0] !== 0x00 || !db.subarray(0, hLen).equals(lHash) || db[i] !== 0x01) throw new Error('decryption error');
  return db.subarray(i + 1);
}

const rawEncrypt = (key: KeyObject, em: Buffer) => publicEncrypt({ key, padding: constants.RSA_NO_PADDING }, em);
const rawDecrypt = (key: KeyObject, block: Buffer) => privateDecrypt({ key, padding: constants.RSA_NO_PADDING }, block);
/** A reply as MMG would produce it: RFC 8017 OAEP over the given bytes, then the demo token encoding. */
const replyToken = (to: KeyObject, bytes: Buffer, hash: Hash = 'sha256', mgfHash: Hash = hash) =>
  toCheckoutToken(rawEncrypt(to, emeOaepEncode(bytes, 512, hash, mgfHash)));

function refusal(fn: () => unknown): MmgCheckoutError {
  try {
    fn();
  } catch (error) {
    expect(error).toBeInstanceOf(MmgCheckoutError);
    return error as MmgCheckoutError;
  }
  throw new Error('expected a refusal');
}

function fatal(fn: () => unknown): string {
  try {
    fn();
  } catch (error) {
    return (error as Error).message;
  }
  throw new Error('expected a FATAL refusal');
}

const request = (over: Partial<MmgCheckoutRequest> = {}): MmgCheckoutRequest => buildCheckoutRequest({
  secretKey: 'not-a-secret',
  amount: '1500',
  merchantId: '0000000001',
  merchantTransactionId: '171234567890112345',
  productDescription: MMG_CHECKOUT_PRODUCT_DESCRIPTION,
  requestInitiationTime: 1_712_345_678,
  merchantName: 'Swift Test',
  ...over,
});

describe('the request, byte for byte as the demo writes it', () => {
  it('carries the seven demo fields in the demo order, with integer unix seconds', () => {
    const r = request();
    expect(Object.keys(r)).toEqual(['secretKey', 'amount', 'merchantId', 'merchantTransactionId', 'productDescription', 'requestInitiationTime', 'merchantName']);
    expect(Number.isInteger(r.requestInitiationTime)).toBe(true);
    expect(requestInitiationTime(new Date('2026-09-24T12:34:56.789Z'))).toBe(1_790_253_296);
    expect(MMG_CHECKOUT_PRODUCT_DESCRIPTION).toBe('Swift weekly fee');
  });

  it('serializes exactly as Python json.dumps(indent=4) with ensure_ascii, then ISO-8859-1', () => {
    // The expected text is Python output for this same object (3.14,
    // json.dumps(obj, indent=4)): every code unit outside printable ASCII
    // escaped in lowercase hex — DEL included, an emoji as its surrogate pair.
    const fixture: MmgCheckoutRequest = {
      secretKey: 'k"\\/',
      amount: '1500',
      merchantId: '0000000001',
      merchantTransactionId: '171234567890112345',
      productDescription: 'caf\u00e9 \u{1F600} \x7f \u2028 \t\n\x01',
      requestInitiationTime: 1712345678,
      merchantName: 'Swift',
    };
    // (Plain strings with doubled backslashes: the expected text holds
    // backslash sequences, and a doubled backslash is the one spelling no
    // editor or tool on the way can turn into the character it names.)
    const python = [
      '{',
      '    "secretKey": "k\\"\\\\/",',
      '    "amount": "1500",',
      '    "merchantId": "0000000001",',
      '    "merchantTransactionId": "171234567890112345",',
      '    "productDescription": "caf\\u00e9 \\ud83d\\ude00 \\u007f \\u2028 \\t\\n\\u0001",',
      '    "requestInitiationTime": 1712345678,',
      '    "merchantName": "Swift"',
      '}',
    ].join('\n');
    const bytes = serializeCheckoutRequest(fixture);
    expect(bytes.toString('latin1')).toBe(python);
    expect(bytes.length).toBe(281);
    expect(Math.max(...bytes)).toBeLessThan(0x7f);
  });

  it('refuses a field that is not what MMG takes', () => {
    expect(refusal(() => request({ amount: '1500.00' })).code).toBe('INVALID_REQUEST');
    expect(refusal(() => request({ merchantId: '592-000' })).code).toBe('INVALID_REQUEST');
    expect(refusal(() => request({ merchantTransactionId: 'ABC123' })).code).toBe('INVALID_REQUEST');
    expect(refusal(() => request({ requestInitiationTime: 1.5 })).code).toBe('INVALID_REQUEST');
    expect(refusal(() => request({ merchantName: ' Swift' })).code).toBe('INVALID_REQUEST');
    expect(refusal(() => request({ merchantName: 'Swïft' })).code).toBe('INVALID_REQUEST');
  });
});

describe('the three defaults, one function each', () => {
  it('[U4] the amount is whole major units as a digit string — cents are refused, never rounded', () => {
    expect(formatCheckoutAmount(fromMajor('1500', 'GYD'))).toBe('1500');
    expect(formatCheckoutAmount(fromMinor(150_000, 'GYD'))).toBe('1500');
    expect(refusal(() => formatCheckoutAmount(fromMajor('1500.50', 'GYD'))).message).toMatch(/never rounded/);
    expect(refusal(() => formatCheckoutAmount(fromMajor('0', 'GYD'))).code).toBe('INVALID_REQUEST');
    expect(refusal(() => formatCheckoutAmount(fromMajor('-5', 'GYD'))).code).toBe('INVALID_REQUEST');
    expect(refusal(() => formatCheckoutAmount(fromMajor('10', 'USD'))).code).toBe('INVALID_REQUEST');
    // [M-36] at the platform ceiling the amount looks minor-scaled: refused, not sent 100x too large.
    expect(refusal(() => formatCheckoutAmount(fromMajor('99999999', 'GYD'))).code).toBe('INVALID_REQUEST');
  });

  it('merchantTransactionId is 18 digits: 13-digit unix milliseconds, then 5 random digits', () => {
    const now = new Date('2026-09-24T12:34:56.789Z');
    const ids = Array.from({ length: 20 }, () => newMerchantTransactionId(now));
    for (const id of ids) {
      expect(id).toMatch(/^\d{18}$/);
      expect(id.slice(0, 13)).toBe(String(now.getTime()));
    }
    expect(new Set(ids.map((id) => id.slice(13))).size).toBeGreaterThan(1);
    expect(refusal(() => newMerchantTransactionId(new Date(999_999_999_999))).code).toBe('INVALID_REQUEST');
  });

  it('the page is the UAT page only outside production; production names an https non-UAT page', () => {
    expect(checkoutPageUrl({ NODE_ENV: 'development' })).toBe(MMG_CHECKOUT_UAT_URL);
    expect(checkoutPageUrl({ NODE_ENV: 'test' })).toBe(MMG_CHECKOUT_UAT_URL);
    expect(fatal(() => checkoutPageUrl({ NODE_ENV: 'production' }))).toMatch(/MMG_CHECKOUT_URL must be set explicitly in production/);
    expect(fatal(() => checkoutPageUrl({ NODE_ENV: 'production', MMG_CHECKOUT_URL: MMG_CHECKOUT_UAT_URL }))).toMatch(/non-UAT/);
    expect(fatal(() => checkoutPageUrl({ NODE_ENV: 'production', MMG_CHECKOUT_URL: MMG_CHECKOUT_SANDBOX_URL }))).toMatch(/non-UAT/);
    expect(checkoutPageUrl({ NODE_ENV: 'production', MMG_CHECKOUT_URL: 'https://checkout.example.test/pay' })).toBe('https://checkout.example.test/pay');
    for (const bad of ['http://checkout.example.test/pay', 'https://checkout.example.test/pay?x=1', 'https://u:p@checkout.example.test/pay', 'not a url']) {
      expect(fatal(() => checkoutPageUrl({ NODE_ENV: 'development', MMG_CHECKOUT_URL: bad })), bad).toMatch(/MMG_CHECKOUT_URL/);
    }
  });
});

describe('RSA-OAEP-SHA256 — interop with an independent RFC 8017 implementation', () => {
  it('MMG can open what we send: EME-OAEP with SHA-256, MGF1-SHA-256 and an empty label', () => {
    const plaintext = serializeCheckoutRequest(request());
    const ciphertext = encryptCheckoutRequest(plaintext, mmg.publicKey);
    expect(ciphertext.length).toBe(512);
    expect(emeOaepDecode(rawDecrypt(mmg.privateKey, ciphertext), 'sha256')).toEqual(plaintext);
  });

  it('we can open what MMG sends under the same parameters, padded or not', () => {
    const token = replyToken(swift.publicKey, Buffer.from(JSON.stringify({ probe: 'reply', n: 7 }), 'utf8'));
    expect(decryptCheckoutResultToken(token, swift.privateKey)).toEqual({ probe: 'reply', n: 7 });
    expect(decryptCheckoutResultToken(token.replace(/=+$/, ''), swift.privateKey)).toEqual({ probe: 'reply', n: 7 });
  });

  it('the digest and the MGF1 hash are load-bearing: SHA-1 OAEP and a SHA-1 MGF1 are neither produced nor accepted', () => {
    const plaintext = serializeCheckoutRequest(request());
    const em = rawDecrypt(mmg.privateKey, encryptCheckoutRequest(plaintext, mmg.publicKey));
    expect(() => emeOaepDecode(em, 'sha1')).toThrow(/decryption error/);
    expect(() => emeOaepDecode(em, 'sha256', 'sha1')).toThrow(/decryption error/);
    const bytes = Buffer.from('{"probe":"reply"}', 'utf8');
    for (const [hash, mgfHash] of [['sha1', 'sha1'], ['sha256', 'sha1'], ['sha1', 'sha256']] as const) {
      const token = replyToken(swift.publicKey, bytes, hash, mgfHash);
      expect(refusal(() => decryptCheckoutResultToken(token, swift.privateKey)).code, `${hash}/${mgfHash}`).toBe('TOKEN_UNREADABLE');
    }
  });

  it('every encryption is fresh (the OAEP seed is random)', () => {
    const plaintext = serializeCheckoutRequest(request());
    expect(encryptCheckoutRequest(plaintext, mmg.publicKey).equals(encryptCheckoutRequest(plaintext, mmg.publicKey))).toBe(false);
  });
});

describe('the size limit is k − 66 of the CONFIGURED key, refused clearly', () => {
  it.each([
    ['4096-bit', 446, () => mmg],
    ['2048-bit', 190, () => small],
  ] as const)('%s key: %d bytes go, one more is refused before Node sees it', (_bits, limit, pairOf) => {
    const key = pairOf().publicKey;
    expect(oaepSha256MaxPlaintextBytes((key.asymmetricKeyDetails!.modulusLength as number) / 8)).toBe(limit);
    const atLimit = Buffer.alloc(limit, 0x41);
    expect(emeOaepDecode(rawDecrypt(pairOf().privateKey, encryptCheckoutRequest(atLimit, key)), 'sha256')).toEqual(atLimit);
    const over = refusal(() => encryptCheckoutRequest(Buffer.alloc(limit + 1, 0x41), key));
    expect(over.code).toBe('REQUEST_TOO_LARGE');
    expect(over.message).toContain(`at most ${limit}`);
  });

  it('a real request does not fit a 2048-bit key, and the refusal carries no request byte', () => {
    const marker = 'MARKER-SECRET-VALUE';
    const plaintext = serializeCheckoutRequest(request({ secretKey: marker, merchantName: 'M'.repeat(64) }));
    expect(plaintext.length).toBeGreaterThan(190);
    const error = refusal(() => encryptCheckoutRequest(plaintext, small.publicKey));
    expect(error.code).toBe('REQUEST_TOO_LARGE');
    expect(error.message).not.toContain(marker);
  });
});

describe('the token and the URL', () => {
  it('the token is standard base64 with + and / swapped and the = padding KEPT (urlsafe_b64encode), unlike Buffer base64url', () => {
    const c4096 = encryptCheckoutRequest(serializeCheckoutRequest(request()), mmg.publicKey);
    const c2048 = encryptCheckoutRequest(Buffer.from('x'), small.publicKey);
    for (const [ciphertext, pad] of [[c4096, '='], [c2048, '==']] as const) {
      const token = toCheckoutToken(ciphertext);
      expect(token).toBe(ciphertext.toString('base64').replace(/\+/g, '-').replace(/\//g, '_'));
      expect(token).toMatch(/^[A-Za-z0-9_-]+={0,2}$/);
      expect(token.endsWith(pad) && !token.endsWith(`${pad}=`)).toBe(true);
      expect(token).not.toBe(ciphertext.toString('base64url'));
      expect(decodeCheckoutToken(token)).toEqual(ciphertext);
    }
    expect(toCheckoutToken(c4096)).toHaveLength(684);
  });

  it('the URL is <page>?token=RAW&merchantId=…&X-Client-ID=… in the demo order', () => {
    const token = toCheckoutToken(encryptCheckoutRequest(serializeCheckoutRequest(request()), mmg.publicKey));
    expect(buildCheckoutUrl(MMG_CHECKOUT_UAT_URL, token, '0000000001', 'client-test'))
      .toBe(`${MMG_CHECKOUT_UAT_URL}?token=${token}&merchantId=0000000001&X-Client-ID=client-test`);
    // The '=' padding rides raw, exactly as the demo writes it; an id that
    // could break the query is percent-encoded instead.
    expect(buildCheckoutUrl(MMG_CHECKOUT_UAT_URL, token, '0000000001', 'a&b=c')).toContain(`token=${token}&`);
    expect(buildCheckoutUrl(MMG_CHECKOUT_UAT_URL, token, '0000000001', 'a&b=c')).toMatch(/&X-Client-ID=a%26b%3Dc$/);
    expect(refusal(() => buildCheckoutUrl(MMG_CHECKOUT_UAT_URL, 'a+b/c', '0000000001', 'x')).code).toBe('INVALID_REQUEST');
  });
});

describe('opening a reply token', () => {
  const utf8Reply = (text: string) => replyToken(swift.publicKey, Buffer.from(text, 'utf8'));

  it('decodes UTF-8: a UTF-8 é is é', () => {
    expect(decryptCheckoutResultToken(utf8Reply('{"message":"café"}'), swift.privateKey)).toEqual({ message: 'café' });
  });

  it('never reads it as ISO-8859-1: a bare Latin-1 é byte is refused, not guessed', () => {
    const latin1 = replyToken(swift.publicKey, Buffer.from('{"message":"caf\xe9"}', 'latin1'));
    expect(refusal(() => decryptCheckoutResultToken(latin1, swift.privateKey)).code).toBe('RESULT_NOT_JSON');
  });

  it('refuses a byte-order mark, a non-JSON reply and a non-object reply', () => {
    expect(refusal(() => decryptCheckoutResultToken(utf8Reply('\ufeff{"a":1}'), swift.privateKey)).code).toBe('RESULT_NOT_JSON');
    expect(refusal(() => decryptCheckoutResultToken(utf8Reply('not json'), swift.privateKey)).code).toBe('RESULT_NOT_JSON');
    expect(refusal(() => decryptCheckoutResultToken(utf8Reply('[1,2]'), swift.privateKey)).code).toBe('RESULT_NOT_OBJECT');
    expect(refusal(() => decryptCheckoutResultToken(utf8Reply('null'), swift.privateKey)).code).toBe('RESULT_NOT_OBJECT');
  });

  it('pads to a multiple of four and no further; a malformed token is refused, never skipped', () => {
    const token = utf8Reply('{"a":1}');
    const bare = token.replace(/=+$/, '');
    expect(bare.length % 4).toBe(3);
    expect(decryptCheckoutResultToken(bare, swift.privateKey)).toEqual({ a: 1 });
    // Wrong padding, too much padding, a standard-base64 character, a space,
    // an impossible length (4n+1) and nothing at all.
    for (const bad of [`${bare}==`, `${bare}===`, `${bare}====`, `${bare.slice(0, -1)}+`, `${bare.slice(0, 10)} ${bare.slice(10)}`, bare.slice(0, 681), '']) {
      expect(refusal(() => decryptCheckoutResultToken(bad, swift.privateKey)).code, JSON.stringify(bad.slice(-6))).toBe('TOKEN_MALFORMED');
    }
    expect(refusal(() => decryptCheckoutResultToken('A'.repeat(5000), swift.privateKey)).code).toBe('TOKEN_MALFORMED');
    // One byte short of an RSA block under this key.
    expect(refusal(() => decryptCheckoutResultToken(toCheckoutToken(decodeCheckoutToken(token).subarray(1)), swift.privateKey)).code).toBe('TOKEN_MALFORMED');
  });

  it('a reply for another key is one generic refusal', () => {
    const forStranger = replyToken(stranger.publicKey, Buffer.from('{"a":1}', 'utf8'));
    const error = refusal(() => decryptCheckoutResultToken(forStranger, swift.privateKey));
    expect(error.code).toBe('TOKEN_UNREADABLE');
    expect(error.message).not.toMatch(/oaep|padding|0x/i);
  });
});

describe('describeShape — names and types for a probe log, never a value', () => {
  it('reports each path with its JSON type', () => {
    const reply = {
      someId: 'VALUE-ONE-SHOULD-NOT-APPEAR',
      code: 0,
      amount: 12.5,
      big: 2 ** 60,
      ok: true,
      none: null,
      nested: { list: [1, 'VALUE-TWO', { deep: 'VALUE-THREE' }] },
      'odd key': 'VALUE-FOUR',
    };
    const shape = describeShape(reply);
    expect(shape).toEqual({
      '["odd key"]': 'string',
      amount: 'number',
      big: 'integer(unsafe)',
      code: 'integer',
      nested: 'object',
      'nested.list': 'array',
      'nested.list[]': 'integer|object|string',
      'nested.list[].deep': 'string',
      none: 'null',
      ok: 'boolean',
      someId: 'string',
    });
    expect(JSON.stringify(shape)).not.toMatch(/VALUE-/);
  });

  it('is bounded, so a hostile reply cannot flood a log', () => {
    const wide = Object.fromEntries(Array.from({ length: 1000 }, (_, i) => [`k${i}`, i]));
    const shape = describeShape(wide);
    expect(Object.keys(shape).length).toBeLessThanOrEqual(201);
    expect(shape['(truncated)']).toBeDefined();
    let deep: Record<string, unknown> = { leaf: 1 };
    for (let i = 0; i < 20; i += 1) deep = { d: deep };
    expect(describeShape(deep)['(truncated)']).toBeDefined();
    expect(describeShape('x')).toEqual({ '(root)': 'string' });
  });
});

// -- Configuration: fail closed, never print a value -----------------------------

function liveEnv(over: Record<string, string | undefined> = {}): Record<string, string | undefined> {
  return {
    NODE_ENV: 'development',
    MMG_DRIVER: 'live',
    MMG_CHECKOUT_ENABLED: '1',
    MMG_CHECKOUT_MERCHANT_ID: '0000000001',
    MMG_CHECKOUT_CLIENT_ID: 'client-test',
    MMG_CHECKOUT_MERCHANT_NAME: 'Swift Test',
    MMG_CHECKOUT_RETURN_ORIGIN: 'https://pay.example.test',
    MMG_CHECKOUT_SECRET_KEY: 'not-a-secret',
    MMG_CHECKOUT_PUBLIC_KEY: pem(mmg.publicKey),
    MMG_CHECKOUT_PRIVATE_KEY: pem(swift.privateKey),
    ...over,
  };
}
const productionEnv = (over: Record<string, string | undefined> = {}) =>
  liveEnv({ NODE_ENV: 'production', MMG_CHECKOUT_URL: 'https://checkout.example.test/mmg-pg/web/payments', ...over });

describe('configuration — off unless exactly 1, then complete or refused', () => {
  it('is off by default, and off means every door refuses', () => {
    expect(() => assertMmgCheckoutConfig({ NODE_ENV: 'production' })).not.toThrow();
    expect(() => assertMmgCheckoutConfig({ NODE_ENV: 'production', MMG_CHECKOUT_ENABLED: '0' })).not.toThrow();
    const off = getMmgCheckoutProvider({ NODE_ENV: 'test' });
    expect(off.driver).toBe('disabled');
    expect(() => off.createCheckout({ amount: fromMajor('1500', 'GYD'), merchantTransactionId: newMerchantTransactionId() }))
      .toThrow(expect.objectContaining({ statusCode: 503, code: 'MMG_CHECKOUT_DISABLED' }));
    expect(() => off.decryptCheckoutResult('AAAA')).toThrow(expect.objectContaining({ code: 'MMG_CHECKOUT_DISABLED' }));
  });

  it.each(['true', 'yes', 'on', ' 1', '1 ', '2'])('refuses the misspelled switch %j', (flag) => {
    expect(fatal(() => assertMmgCheckoutConfig({ NODE_ENV: 'development', MMG_CHECKOUT_ENABLED: flag }))).toMatch(/MMG_CHECKOUT_ENABLED must be exactly 0 or 1/);
  });

  it('accepts a complete live configuration, with the UAT page outside production', () => {
    expect(() => assertMmgCheckoutConfig(liveEnv())).not.toThrow();
    const config = loadMmgCheckoutConfig(liveEnv());
    expect(config.checkoutPage).toBe(MMG_CHECKOUT_UAT_URL);
    expect(config.returnOrigin).toBe('https://pay.example.test');
    expect(() => assertMmgCheckoutConfig(productionEnv())).not.toThrow();
  });

  it.each([
    'MMG_CHECKOUT_MERCHANT_ID', 'MMG_CHECKOUT_CLIENT_ID', 'MMG_CHECKOUT_MERCHANT_NAME', 'MMG_CHECKOUT_RETURN_ORIGIN',
    'MMG_CHECKOUT_SECRET_KEY', 'MMG_CHECKOUT_PUBLIC_KEY', 'MMG_CHECKOUT_PRIVATE_KEY',
  ])('enabled with the live driver, a missing %s refuses to start', (name) => {
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ [name]: undefined })))).toMatch(new RegExp(`${name}.*required`));
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ [name]: '' })))).toMatch(new RegExp(`${name}.*required`));
  });

  it('names the variable and never echoes its value', () => {
    const cases: Array<[string, string]> = [
      ['MMG_CHECKOUT_MERCHANT_ID', 'LEAKME-12ab'],
      ['MMG_CHECKOUT_CLIENT_ID', 'LEAKME client'],
      ['MMG_CHECKOUT_MERCHANT_NAME', ' LEAKME'],
      ['MMG_CHECKOUT_SECRET_KEY', 'LEAKME-secret '],
      ['MMG_CHECKOUT_RETURN_ORIGIN', 'https://leakme.example.test/path'],
      ['MMG_CHECKOUT_PUBLIC_KEY', 'LEAKME-not-a-key'],
      ['MMG_CHECKOUT_PRIVATE_KEY', 'LEAKME-not-a-key'],
      ['MMG_CHECKOUT_URL', 'http://leakme.example.test/pay'],
    ];
    for (const [name, value] of cases) {
      const message = fatal(() => assertMmgCheckoutConfig(liveEnv({ [name]: value })));
      expect(message, name).toContain(name);
      expect(message.toLowerCase(), name).not.toContain('leakme');
    }
  });

  it('refuses a PRIVATE key where the public key goes, rather than quietly deriving from it', () => {
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PUBLIC_KEY: pem(mmg.privateKey) }))))
      .toMatch(/MMG_CHECKOUT_PUBLIC_KEY holds a PRIVATE key/);
  });

  it('reads a PEM whose newlines an env file forced into literal \\n', () => {
    const escaped = pem(mmg.publicKey).trim().replace(/\n/g, '\\n');
    expect(escaped).not.toContain('\n');
    expect(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PUBLIC_KEY: escaped }))).not.toThrow();
  });

  it('reads the private key from its secret FILE (one trailing newline stripped by the loader)', () => {
    const dir = mkdtempSync(join(tmpdir(), 'swift-mmg-checkout-'));
    try {
      const path = join(dir, 'MMG_CHECKOUT_PRIVATE_KEY');
      writeFileSync(path, pem(swift.privateKey), { mode: 0o600 });
      const env = liveEnv({ MMG_CHECKOUT_PRIVATE_KEY: undefined, MMG_CHECKOUT_PRIVATE_KEY_FILE: path });
      expect(applySecretFiles(env)).toEqual(['MMG_CHECKOUT_PRIVATE_KEY']);
      expect(() => assertMmgCheckoutConfig(env)).not.toThrow();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('refuses a key under 2048 bits, an encrypted private key, and a non-RSA key', async () => {
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PUBLIC_KEY: pem(weak.publicKey) })))).toMatch(/MMG_CHECKOUT_PUBLIC_KEY is a 1024-bit key/);
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PRIVATE_KEY: pem(weak.privateKey) })))).toMatch(/MMG_CHECKOUT_PRIVATE_KEY is a 1024-bit key/);
    const locked = swift.privateKey.export({ type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase: 'test-only' }).toString();
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PRIVATE_KEY: locked })))).toMatch(/unencrypted RSA private key/);
    const ec = await new Promise<Pair>((resolve, reject) => {
      generateKeyPair('ec', { namedCurve: 'prime256v1' }, (err, publicKey, privateKey) => (err ? reject(err) : resolve({ publicKey, privateKey })));
    });
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PUBLIC_KEY: pem(ec.publicKey) })))).toMatch(/MMG_CHECKOUT_PUBLIC_KEY must be an RSA key/);
  });

  it('a key too small for this merchant request fails the deploy, not the first partner', () => {
    const message = fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_PUBLIC_KEY: pem(small.publicKey) })));
    expect(message).toMatch(/MMG_CHECKOUT_PUBLIC_KEY is a 2048-bit key/);
    expect(message).toMatch(/at most 190 bytes/);
  });

  it('the return origin is an https origin (plain http only for localhost outside production)', () => {
    expect(loadMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_RETURN_ORIGIN: 'http://localhost:3000' })).returnOrigin).toBe('http://localhost:3000');
    expect(fatal(() => assertMmgCheckoutConfig(productionEnv({ MMG_CHECKOUT_RETURN_ORIGIN: 'http://localhost:3000' })))).toMatch(/MMG_CHECKOUT_RETURN_ORIGIN must be an https origin/);
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_RETURN_ORIGIN: 'http://pay.example.test' })))).toMatch(/https origin/);
    for (const notAnOrigin of ['https://pay.example.test/pay/mmg', 'https://pay.example.test?x=1', 'https://u:p@pay.example.test']) {
      expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_CHECKOUT_RETURN_ORIGIN: notAnOrigin }))), notAnOrigin).toMatch(/origin only/);
    }
  });

  it('production: never the sandbox, never a UAT page, never an implicit page', () => {
    expect(fatal(() => assertMmgCheckoutConfig({ NODE_ENV: 'production', MMG_CHECKOUT_ENABLED: '1' }))).toMatch(/needs MMG_DRIVER=live/);
    expect(fatal(() => assertMmgCheckoutConfig(productionEnv({ MMG_DRIVER: 'sandbox' })))).toMatch(/needs MMG_DRIVER=live/);
    expect(fatal(() => assertMmgCheckoutConfig(productionEnv({ MMG_CHECKOUT_URL: undefined })))).toMatch(/MMG_CHECKOUT_URL must be set explicitly/);
    expect(fatal(() => assertMmgCheckoutConfig(productionEnv({ MMG_CHECKOUT_URL: MMG_CHECKOUT_UAT_URL })))).toMatch(/non-UAT/);
    expect(fatal(() => assertMmgCheckoutConfig(liveEnv({ MMG_DRIVER: 'mock' })))).toMatch(/sandbox or live/);
  });
});

describe('the provider seam', () => {
  it('follows MMG_DRIVER once enabled; production never gets the sandbox', () => {
    expect(getMmgCheckoutProvider({ NODE_ENV: 'development', MMG_CHECKOUT_ENABLED: '1' }).driver).toBe('sandbox');
    expect(getMmgCheckoutProvider(liveEnv()).driver).toBe('live');
    expect(() => getMmgCheckoutProvider({ NODE_ENV: 'production', MMG_CHECKOUT_ENABLED: '1', MMG_DRIVER: 'sandbox' })).toThrow(/forbidden in production/);
    expect(() => getMmgCheckoutProvider({ NODE_ENV: 'development', MMG_CHECKOUT_ENABLED: '1', MMG_DRIVER: 'mock' })).toThrow(/Unknown MMG_DRIVER/);
  });

  it('the live provider builds the demo URL, and MMG can read the request inside it', () => {
    const live = getMmgCheckoutProvider(liveEnv());
    const merchantTransactionId = newMerchantTransactionId();
    const now = new Date('2026-09-24T12:00:00Z');
    const session = live.createCheckout({ amount: fromMajor('2500', 'GYD'), merchantTransactionId, now });
    expect(session).toMatchObject({ merchantTransactionId, amount: '2500', requestInitiationTime: requestInitiationTime(now) });
    const match = /^(.*)\?token=([A-Za-z0-9_-]+=*)&merchantId=0000000001&X-Client-ID=client-test$/.exec(session.checkoutUrl);
    expect(match?.[1]).toBe(MMG_CHECKOUT_UAT_URL);
    const opened = emeOaepDecode(rawDecrypt(mmg.privateKey, decodeCheckoutToken(match![2] as string)), 'sha256');
    expect(opened.toString('latin1')).toBe(serializeCheckoutRequest(request({
      amount: '2500', merchantTransactionId, requestInitiationTime: requestInitiationTime(now),
    })).toString('latin1'));
    // Replies open with the OTHER configured key: the private key, never the request key.
    expect(live.decryptCheckoutResult(replyToken(swift.publicKey, Buffer.from('{"x":1}')))).toEqual({ x: 1 });
    expect(refusal(() => live.decryptCheckoutResult(replyToken(mmg.publicKey, Buffer.from('{"x":1}')))).code).toBe('TOKEN_UNREADABLE');
  });

  it('the sandbox runs the real code under its own keys and plays MMG on both sides', () => {
    const sandbox = new SandboxMmgCheckoutProvider({ request: mmg, result: swift });
    const merchantTransactionId = newMerchantTransactionId();
    const now = new Date('2026-09-24T12:00:00Z');
    const session = sandbox.createCheckout({ amount: fromMajor('1500', 'GYD'), merchantTransactionId, now });
    expect(session.checkoutUrl.startsWith(`${MMG_CHECKOUT_SANDBOX_URL}?token=`)).toBe(true);
    const seen = sandbox.sandboxReadRequest(session.checkoutUrl);
    expect(Object.keys(seen)).toEqual(['secretKey', 'amount', 'merchantId', 'merchantTransactionId', 'productDescription', 'requestInitiationTime', 'merchantName']);
    expect(seen).toMatchObject({ amount: '1500', merchantTransactionId, productDescription: 'Swift weekly fee', requestInitiationTime: requestInitiationTime(now) });
    for (const padded of [true, false]) {
      expect(sandbox.decryptCheckoutResult(sandbox.sandboxReplyToken({ any: 'field', n: 1 }, { padded }))).toEqual({ any: 'field', n: 1 });
    }
    expect(sandbox.sandboxReplyToken({ a: 1 }, { padded: false })).not.toMatch(/=$/);
  });
});
