#!/usr/bin/env bash
#
# Generate the secrets a Swift production deploy cannot boot without.
#
# Writes deploy/.env and NOTHING else. That path is covered by deploy/.gitignore
# (`.env`, `.env.*`, with `!.env.deploy.example` as the one exception), verified
# with `git check-ignore` — but note that .gitignore only protects you from
# porcelain. `git update-index --cacheinfo` is plumbing and stages silently, so
# never hand-stage this file.
#
# Every value here is generated locally with openssl. Nothing is transmitted,
# nothing is printed: the script reports which variables it WROTE, never what
# it wrote them to. If you need to read one, read the file.
#
# The four boot guards these satisfy, from apps/api/src/utils/boot-config.ts:
#   MASTER_KEK              32 bytes, base64. Unset ⇒ verification documents
#                           (government IDs, selfies) are stored UNENCRYPTED.
#                           The guard decodes and checks the length is exactly 32.
#   OTP_HASH_SECRET         >=32 chars (or a >=32 char JWT_SECRET). OTP records
#                           are six digits; an unkeyed hash is recoverable
#                           offline in seconds.
#   STORAGE_SIGNING_SECRET  The ONLY gate on the unauthenticated document-render
#                           route. The default value is published in a PUBLIC
#                           repo, so anyone could forge a token for any docId
#                           and stream a decrypted ID.
#   JWT_SECRET              Session signing.
#
# CONSENT_IP_PEPPER is not fatal but degrades SILENTLY: under 32 characters,
# hashIp() returns null and the consent ledger simply stops recording IP
# attribution. Generated here so that never happens by omission.
#
# POSTGRES_PASSWORD and MEILISEARCH_KEY are infrastructure credentials consumed
# by deploy/docker-compose.yml.
#
# Usage:
#   ./deploy/gen-secrets.sh            # create deploy/.env, refuse if it exists
#   ./deploy/gen-secrets.sh --force    # rotate: back the old file up first
#
# ROTATION IS NOT FREE. Re-generating MASTER_KEK makes every already-encrypted
# verification document undecryptable, and re-generating STORAGE_SIGNING_SECRET
# invalidates every signed URL in flight. --force takes a timestamped backup
# and says so; it cannot un-break data that was encrypted under the old key.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HERE/.env"
TEMPLATE="$HERE/.env.deploy.example"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,44p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $arg (try --help)" >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null 2>&1 || {
  echo "FATAL: openssl not found. Every secret here is generated locally with it; there is no fallback worth having." >&2
  exit 1
}

if [ -e "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
  cat >&2 <<'MSG'
FATAL: deploy/.env already exists.

Refusing to overwrite it. If this deploy has ever run, that file holds the
MASTER_KEK that every stored verification document was encrypted under, and
replacing it makes those documents undecryptable — permanently.

If you genuinely mean to rotate, re-run with --force (the old file is backed up
first), and understand that a rotated MASTER_KEK does not re-encrypt anything
that already exists.
MSG
  exit 1
fi

if [ -e "$ENV_FILE" ]; then
  BACKUP="$ENV_FILE.backup.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  chmod 600 "$BACKUP"
  echo "rotating — previous file backed up to $(basename "$BACKUP")"
fi

# 32 raw bytes → base64. The guard does Buffer.from(kek,'base64').length !== 32,
# so this must be exactly 32 bytes BEFORE encoding, not 32 characters after.
gen_kek()    { openssl rand -base64 32; }
# 48 raw bytes → ~64 base64 chars, comfortably over every >=32 check.
gen_secret() { openssl rand -base64 48 | tr -d '\n=' ; }

umask 077
{
  echo "# Generated by deploy/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# SECRETS. Never commit, never paste into a ticket, never echo in CI logs."
  echo "#"
  echo "# Rotating MASTER_KEK makes existing verification documents undecryptable."
  echo "# Rotating STORAGE_SIGNING_SECRET invalidates every signed URL in flight."
  echo
  echo "MASTER_KEK=$(gen_kek)"
  echo "JWT_SECRET=$(gen_secret)"
  echo "OTP_HASH_SECRET=$(gen_secret)"
  echo "STORAGE_SIGNING_SECRET=$(gen_secret)"
  echo "CONSENT_IP_PEPPER=$(gen_secret)"
  echo "POSTGRES_PASSWORD=$(gen_secret)"
  echo "MEILISEARCH_KEY=$(gen_secret)"
  echo
  echo "# ---------------------------------------------------------------------"
  echo "# Everything below is NOT a secret and is copied from .env.deploy.example"
  echo "# so this file is a complete deploy env. Review it — the defaults are"
  echo "# development-safe, which means several of them are exactly what the"
  echo "# production boot guards refuse to start on (KYC_PROVIDER=sandbox,"
  echo "# PAYMENT_PROVIDER=sandbox, MMG_DRIVER=sandbox, NOTIFICATION_PROVIDER=dev)."
  echo "# Run ./deploy/preflight.sh to see exactly which ones would refuse."
  echo "# ---------------------------------------------------------------------"
  echo
  if [ -f "$TEMPLATE" ]; then
    # Drop the three the template also names, so the generated values above win.
    grep -vE '^(POSTGRES_PASSWORD|MEILISEARCH_KEY|JWT_SECRET)=' "$TEMPLATE"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Report names only. A script that prints secrets puts them in a scrollback
# buffer, a CI log, and a screen recording.
echo "wrote $(basename "$ENV_FILE") (mode 600) with generated values for:"
for v in MASTER_KEK JWT_SECRET OTP_HASH_SECRET STORAGE_SIGNING_SECRET CONSENT_IP_PEPPER POSTGRES_PASSWORD MEILISEARCH_KEY; do
  echo "  - $v"
done

# Prove the one value with a hard length requirement actually meets it, rather
# than discovering it at boot on the server.
KEK_BYTES=$(grep '^MASTER_KEK=' "$ENV_FILE" | cut -d= -f2- | openssl base64 -d 2>/dev/null | wc -c | tr -d ' ')
if [ "$KEK_BYTES" != "32" ]; then
  echo "FATAL: MASTER_KEK decoded to ${KEK_BYTES} bytes, not 32 — the boot guard would refuse. Not usable." >&2
  exit 1
fi
echo "verified: MASTER_KEK decodes to exactly 32 bytes"
echo
echo "Next: ./deploy/preflight.sh — it reads this file and reports, per boot guard,"
echo "what is PRESENT, MISSING, or WILL-REFUSE-IN-PRODUCTION."
