-- [DOC-1 §4.3 · P1-2] Subjects: PERSON / BUSINESS / VEHICLE, subject links with validity windows, one
-- profile table per kind, and VerificationDocument.subjectId (EXPAND beside userId; legacy rows are filled
-- by `pnpm doc1:backfill-subjects`). Schema half generated by `prisma migrate diff`; the tenant wall (RLS +
-- lineage triggers) by src/lib/tenant-rls.ts (rlsDdlFor, tenantLineageDdl).

-- CreateEnum
CREATE TYPE "SubjectRelation" AS ENUM ('SELF', 'OWNER', 'DIRECTOR', 'ASSIGNED_DRIVER', 'OPERATOR');

-- AlterTable
ALTER TABLE "verification_documents" ADD COLUMN     "subjectId" UUID;

-- CreateTable
CREATE TABLE "subject" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" TEXT NOT NULL DEFAULT 'swift-default',
    "kind" "DocSubjectKind" NOT NULL,
    "countryCode" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "mergedIntoId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "subject_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subject_link" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" TEXT NOT NULL DEFAULT 'swift-default',
    "accountId" TEXT NOT NULL,
    "subjectId" UUID NOT NULL,
    "relation" "SubjectRelation" NOT NULL,
    "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "validTo" TIMESTAMP(3),

    CONSTRAINT "subject_link_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "person_profile" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" TEXT NOT NULL DEFAULT 'swift-default',
    "subjectId" UUID NOT NULL,
    "accountId" TEXT NOT NULL,
    "verificationLevel" TEXT NOT NULL DEFAULT 'NONE',
    "verifiedAt" TIMESTAMP(3),

    CONSTRAINT "person_profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_profile" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" TEXT NOT NULL DEFAULT 'swift-default',
    "subjectId" UUID NOT NULL,
    "ownerAccountId" TEXT NOT NULL,
    "tradingName" TEXT,
    "entityForm" TEXT NOT NULL DEFAULT 'UNREGISTERED',
    "tier" TEXT NOT NULL DEFAULT 'TIER_UNREGISTERED',

    CONSTRAINT "business_profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_profile" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" TEXT NOT NULL DEFAULT 'swift-default',
    "subjectId" UUID NOT NULL,
    "registrationMark" TEXT NOT NULL,
    "countryCode" TEXT NOT NULL,
    "vehicleKind" TEXT NOT NULL,
    "make" TEXT,
    "model" TEXT,
    "year" INTEGER,
    "colour" TEXT,
    "registeredById" TEXT NOT NULL,

    CONSTRAINT "vehicle_profile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "subject_tenantId_kind_countryCode_idx" ON "subject"("tenantId", "kind", "countryCode");

-- CreateIndex
CREATE INDEX "subject_createdById_idx" ON "subject"("createdById");

-- CreateIndex
CREATE INDEX "subject_mergedIntoId_idx" ON "subject"("mergedIntoId");

-- CreateIndex
CREATE INDEX "subject_link_subjectId_idx" ON "subject_link"("subjectId");

-- CreateIndex
CREATE INDEX "subject_link_tenantId_accountId_idx" ON "subject_link"("tenantId", "accountId");

-- CreateIndex
CREATE UNIQUE INDEX "subject_link_accountId_subjectId_relation_validFrom_key" ON "subject_link"("accountId", "subjectId", "relation", "validFrom");

-- CreateIndex
CREATE UNIQUE INDEX "person_profile_subjectId_key" ON "person_profile"("subjectId");

-- CreateIndex
CREATE UNIQUE INDEX "person_profile_accountId_key" ON "person_profile"("accountId");

-- CreateIndex
CREATE UNIQUE INDEX "business_profile_subjectId_key" ON "business_profile"("subjectId");

-- CreateIndex
CREATE UNIQUE INDEX "business_profile_ownerAccountId_key" ON "business_profile"("ownerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_profile_subjectId_key" ON "vehicle_profile"("subjectId");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_profile_registrationMark_countryCode_key" ON "vehicle_profile"("registrationMark", "countryCode");

-- CreateIndex
CREATE INDEX "verification_documents_subjectId_idx" ON "verification_documents"("subjectId");

-- AddForeignKey
ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject" ADD CONSTRAINT "subject_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject" ADD CONSTRAINT "subject_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject" ADD CONSTRAINT "subject_mergedIntoId_fkey" FOREIGN KEY ("mergedIntoId") REFERENCES "subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_link" ADD CONSTRAINT "subject_link_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_link" ADD CONSTRAINT "subject_link_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_link" ADD CONSTRAINT "subject_link_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "person_profile" ADD CONSTRAINT "person_profile_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "person_profile" ADD CONSTRAINT "person_profile_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_profile" ADD CONSTRAINT "business_profile_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_profile" ADD CONSTRAINT "business_profile_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vehicle_profile" ADD CONSTRAINT "vehicle_profile_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vehicle_profile" ADD CONSTRAINT "vehicle_profile_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── tenant wall ──
ALTER TABLE "subject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subject" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "subject";
CREATE POLICY "tenant_isolation" ON "subject"
      USING (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')))
      WITH CHECK (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')));
ALTER TABLE "subject_link" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subject_link" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "subject_link";
CREATE POLICY "tenant_isolation" ON "subject_link"
      USING (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')))
      WITH CHECK (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')));
ALTER TABLE "person_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "person_profile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "person_profile";
CREATE POLICY "tenant_isolation" ON "person_profile"
      USING (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')))
      WITH CHECK (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')));
ALTER TABLE "business_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_profile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "business_profile";
CREATE POLICY "tenant_isolation" ON "business_profile"
      USING (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')))
      WITH CHECK (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')));
ALTER TABLE "vehicle_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vehicle_profile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "vehicle_profile";
CREATE POLICY "tenant_isolation" ON "vehicle_profile"
      USING (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')))
      WITH CHECK (("tenantId" = current_setting('app.current_tenant', true)
      OR pg_has_role(current_user, 'swift_bypass_rls', 'MEMBER')));
CREATE OR REPLACE FUNCTION subject_tenant_matches_creator() RETURNS trigger AS $$
      DECLARE parent_tenant TEXT;
      BEGIN
        SELECT "tenantId" FROM users WHERE id = NEW."createdById" INTO parent_tenant;
        IF parent_tenant IS NULL THEN
          -- An UPDATE that unlinks the owner (an FK SET NULL when a mover or user is
          -- deleted) leaves the row's tenant as it was; only a NEW row with no owner is refused.
          IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
          RAISE EXCEPTION 'subject row % names users row %, which does not exist or is not visible from this tenant [STA-1 lineage]',
            NEW.id, NEW."createdById" USING ERRCODE = 'check_violation';
        END IF;
        -- The default means "unstamped": derive the truth from the parent.
        IF NEW."tenantId" = 'swift-default' AND parent_tenant <> 'swift-default' THEN
          NEW."tenantId" := parent_tenant;
        ELSIF parent_tenant <> NEW."tenantId" THEN
          RAISE EXCEPTION 'subject row % names tenant % but its users row % is in tenant % [STA-1 lineage]',
            NEW.id, NEW."tenantId", NEW."createdById", parent_tenant USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
      END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS subject_tenant_matches_creator ON subject;
CREATE TRIGGER subject_tenant_matches_creator BEFORE INSERT OR UPDATE OF "tenantId", "createdById" ON subject FOR EACH ROW EXECUTE FUNCTION subject_tenant_matches_creator();
CREATE OR REPLACE FUNCTION subject_link_tenant_matches_account() RETURNS trigger AS $$
      DECLARE parent_tenant TEXT;
      BEGIN
        SELECT "tenantId" FROM users WHERE id = NEW."accountId" INTO parent_tenant;
        IF parent_tenant IS NULL THEN
          -- An UPDATE that unlinks the owner (an FK SET NULL when a mover or user is
          -- deleted) leaves the row's tenant as it was; only a NEW row with no owner is refused.
          IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
          RAISE EXCEPTION 'subject_link row % names users row %, which does not exist or is not visible from this tenant [STA-1 lineage]',
            NEW.id, NEW."accountId" USING ERRCODE = 'check_violation';
        END IF;
        -- The default means "unstamped": derive the truth from the parent.
        IF NEW."tenantId" = 'swift-default' AND parent_tenant <> 'swift-default' THEN
          NEW."tenantId" := parent_tenant;
        ELSIF parent_tenant <> NEW."tenantId" THEN
          RAISE EXCEPTION 'subject_link row % names tenant % but its users row % is in tenant % [STA-1 lineage]',
            NEW.id, NEW."tenantId", NEW."accountId", parent_tenant USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
      END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS subject_link_tenant_matches_account ON subject_link;
CREATE TRIGGER subject_link_tenant_matches_account BEFORE INSERT OR UPDATE OF "tenantId", "accountId" ON subject_link FOR EACH ROW EXECUTE FUNCTION subject_link_tenant_matches_account();
CREATE OR REPLACE FUNCTION person_profile_tenant_matches_subject() RETURNS trigger AS $$
      DECLARE parent_tenant TEXT;
      BEGIN
        SELECT "tenantId" FROM subject WHERE id = NEW."subjectId" INTO parent_tenant;
        IF parent_tenant IS NULL THEN
          -- An UPDATE that unlinks the owner (an FK SET NULL when a mover or user is
          -- deleted) leaves the row's tenant as it was; only a NEW row with no owner is refused.
          IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
          RAISE EXCEPTION 'person_profile row % names subject row %, which does not exist or is not visible from this tenant [STA-1 lineage]',
            NEW.id, NEW."subjectId" USING ERRCODE = 'check_violation';
        END IF;
        -- The default means "unstamped": derive the truth from the parent.
        IF NEW."tenantId" = 'swift-default' AND parent_tenant <> 'swift-default' THEN
          NEW."tenantId" := parent_tenant;
        ELSIF parent_tenant <> NEW."tenantId" THEN
          RAISE EXCEPTION 'person_profile row % names tenant % but its subject row % is in tenant % [STA-1 lineage]',
            NEW.id, NEW."tenantId", NEW."subjectId", parent_tenant USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
      END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS person_profile_tenant_matches_subject ON person_profile;
CREATE TRIGGER person_profile_tenant_matches_subject BEFORE INSERT OR UPDATE OF "tenantId", "subjectId" ON person_profile FOR EACH ROW EXECUTE FUNCTION person_profile_tenant_matches_subject();
CREATE OR REPLACE FUNCTION business_profile_tenant_matches_subject() RETURNS trigger AS $$
      DECLARE parent_tenant TEXT;
      BEGIN
        SELECT "tenantId" FROM subject WHERE id = NEW."subjectId" INTO parent_tenant;
        IF parent_tenant IS NULL THEN
          -- An UPDATE that unlinks the owner (an FK SET NULL when a mover or user is
          -- deleted) leaves the row's tenant as it was; only a NEW row with no owner is refused.
          IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
          RAISE EXCEPTION 'business_profile row % names subject row %, which does not exist or is not visible from this tenant [STA-1 lineage]',
            NEW.id, NEW."subjectId" USING ERRCODE = 'check_violation';
        END IF;
        -- The default means "unstamped": derive the truth from the parent.
        IF NEW."tenantId" = 'swift-default' AND parent_tenant <> 'swift-default' THEN
          NEW."tenantId" := parent_tenant;
        ELSIF parent_tenant <> NEW."tenantId" THEN
          RAISE EXCEPTION 'business_profile row % names tenant % but its subject row % is in tenant % [STA-1 lineage]',
            NEW.id, NEW."tenantId", NEW."subjectId", parent_tenant USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
      END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS business_profile_tenant_matches_subject ON business_profile;
CREATE TRIGGER business_profile_tenant_matches_subject BEFORE INSERT OR UPDATE OF "tenantId", "subjectId" ON business_profile FOR EACH ROW EXECUTE FUNCTION business_profile_tenant_matches_subject();
CREATE OR REPLACE FUNCTION vehicle_profile_tenant_matches_subject() RETURNS trigger AS $$
      DECLARE parent_tenant TEXT;
      BEGIN
        SELECT "tenantId" FROM subject WHERE id = NEW."subjectId" INTO parent_tenant;
        IF parent_tenant IS NULL THEN
          -- An UPDATE that unlinks the owner (an FK SET NULL when a mover or user is
          -- deleted) leaves the row's tenant as it was; only a NEW row with no owner is refused.
          IF TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
          RAISE EXCEPTION 'vehicle_profile row % names subject row %, which does not exist or is not visible from this tenant [STA-1 lineage]',
            NEW.id, NEW."subjectId" USING ERRCODE = 'check_violation';
        END IF;
        -- The default means "unstamped": derive the truth from the parent.
        IF NEW."tenantId" = 'swift-default' AND parent_tenant <> 'swift-default' THEN
          NEW."tenantId" := parent_tenant;
        ELSIF parent_tenant <> NEW."tenantId" THEN
          RAISE EXCEPTION 'vehicle_profile row % names tenant % but its subject row % is in tenant % [STA-1 lineage]',
            NEW.id, NEW."tenantId", NEW."subjectId", parent_tenant USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
      END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS vehicle_profile_tenant_matches_subject ON vehicle_profile;
CREATE TRIGGER vehicle_profile_tenant_matches_subject BEFORE INSERT OR UPDATE OF "tenantId", "subjectId" ON vehicle_profile FOR EACH ROW EXECUTE FUNCTION vehicle_profile_tenant_matches_subject();
