import { fireEvent, screen, within } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { AppShell } from './AppShell';
import { mockApi, renderWithQuery } from '@/test/test-utils';
const nav = vi.hoisted(() => ({ pathname: '/verification', replace: vi.fn(), push: vi.fn() }));
vi.mock('next/navigation', () => ({ usePathname: () => nav.pathname, useRouter: () => nav }));
it('provides a mobile drawer with trapped focus and closes on Escape, overlay, and navigation; retains desktop sidebar', async () => {
  mockApi(() => ({ body: { data: { user: { id: 'admin', roles: ['ADMIN'] } } } }));
  const { user, rerender } = renderWithQuery(<AppShell><p>Workspace</p></AppShell>);
  const menu = await screen.findByRole('button', { name: 'Open navigation' });
  expect(document.querySelector('[data-desktop-sidebar]')?.className).toContain('md:flex');
  await user.click(menu);
  let drawer = screen.getByRole('dialog', { name: 'Navigation' });
  const close = within(drawer).getByRole('button', { name: 'Close navigation' });
  expect(document.activeElement).toBe(close);
  fireEvent.keyDown(drawer, { key: 'Tab', shiftKey: true });
  expect(document.activeElement).toBe(within(drawer).getAllByRole('link').at(-1));
  fireEvent.keyDown(drawer, { key: 'Tab' });
  expect(document.activeElement).toBe(close);
  await user.keyboard('{Escape}');
  expect(screen.queryByRole('dialog')).toBeNull();
  expect(document.activeElement).toBe(menu);
  await user.click(menu);
  await user.click(screen.getByTestId('navigation-overlay'));
  expect(screen.queryByRole('dialog')).toBeNull();
  await user.click(menu);
  drawer = screen.getByRole('dialog', { name: 'Navigation' });
  await user.click(within(drawer).getByRole('link', { name: 'Documents' }));
  expect(screen.queryByRole('dialog')).toBeNull();
  await user.click(menu);
  nav.pathname = '/orders';
  rerender(<AppShell><p>Orders workspace</p></AppShell>);
  expect(screen.queryByRole('dialog')).toBeNull();
  nav.pathname = '/verification';
});
