/**
 * [STA-1 Part 6] The store-review CONTENT PACK: what an App Store / Play
 * reviewer finds after signing in with the review credential.
 *
 * Five FICTIONAL Georgetown-style businesses — a kitchen, a grocer, a bakery &
 * cafe, a personal-care convenience store and a barber (services, booked by
 * appointment) — with menus priced in GYD, categories and opening hours. Every
 * store is ACTIVE, verified, open and accepting orders INSIDE the REVIEW
 * tenant only, so the reviewer can browse, add to the cart and reach
 * checkout. Placing the order is refused with a friendly message (the
 * review-tenant checkout rule in order.service.ts): no order, no money rail
 * (DL-5), no provider is ever touched.
 *
 *   - FICTION ONLY. No real person, business, address or phone number. Store
 *     addresses say "(demo address)"; the one synthetic owner is "Demo Store
 *     Owner" on an undialable +5920009700NN identifier (a leading 0 after +592
 *     is never a subscriber number); no store publishes a phone or an MMG link.
 *     `PACK_NAME_DENYLIST` keeps well-known real Guyanese and global brand
 *     names out of every name (content-pack test).
 *   - TENANT-WALLED. `assertReviewTenant` refuses every tenant that is not a
 *     purge-protected REVIEW tenant (swift-default and every operator
 *     included) BEFORE any write; every row names the review tenant
 *     explicitly; and with the scoped client the writes also run inside that
 *     tenant, where the wall stamps the tenant last.
 *   - IDEMPOTENT. Every row's id is derived from (pack version, tenant, logical
 *     key), and every write is an upsert keyed on that id AND the tenant — a
 *     colliding id in another tenant fails loudly instead of being adopted.
 *     Re-running heals drift (a darkened store, an edited price) back to the
 *     pack and never deletes anything (the tenant is purge-protected).
 *   - IMAGES: Swift-generated, never downloaded. Each item's picture is drawn
 *     by pack-image.ts from the pack's own words (licence/source recorded
 *     there and in PACK_IMAGE_LICENCE) and served by the public uploads route.
 *   - NO RATINGS. Ratings belong to real orders; the stores show "New".
 *   - PARTNERS. The same seed makes the tenant's RIDER and DRIVER credential
 *     accounts verified partners inside the fiction (partner-pack.ts), so
 *     a reviewer can sign in as either and go online. PRESENT includes them.
 */
import crypto from 'node:crypto';
import type { PrismaClient, Prisma, VendorType, FulfillmentType } from '@prisma/client';
import { runWithTenant, runWithoutTenant } from '../../plugins/tenant-context';
import { LAUNCH_CITY } from './gate';
import { renderPackPicture, isLetterable } from './pack-image';
import { seedReviewPartners, reviewPartnerFacts, type ReviewPartnerFacts } from './partner-pack';

export const REVIEW_CONTENT_PACK_VERSION = 'review-pack-v1';
/** A review tenant's id/slug names the fiction as such (same rule as provision). */
export const REVIEW_SLUG_PATTERN = /^review-[a-z0-9-]{2,40}$/;
/** Where the pack's pictures live on the public uploads route (items/ tree). */
export const REVIEW_PACK_IMAGE_DIR = 'review-pack/v1/';
export const PACK_IMAGE_LICENCE =
  'Generated by Swift (apps/api/src/modules/review/pack-image.ts): solid colour + Swift-authored pixel lettering of the fictional names below. No third-party, stock or downloaded material.';
/** The synthetic owner's identifier block: +592 then a leading 0 — never a subscriber number. */
export const PACK_OWNER_PHONE_PREFIX = '+5920009700';

/** Real brand / business tokens no pack name may contain (case-insensitive). */
export const PACK_NAME_DENYLIST: readonly string[] = [
  'shanta', 'bakewell', 'royal castle', "church's", 'kfc', 'popeyes', 'massy', 'bounty', 'survival',
  "nigel's", 'dsl', 'demico', 'brown betty', 'oasis', "german's", "hack's", 'jerries', "mario's",
  'pizza hut', 'starbucks', 'subway', 'digicel', 'gtt', 'banks dih', 'guyana stores', 'fogarty', 'courts',
  'mmg', 'mobile money', 'swift', 'westbridge', 'amazon', 'walmart', 'mcdonald',
];

interface PackItem {
  key: string;
  name: string;
  description: string;
  /** GYD, whole dollars. */
  price: number;
  unit?: string;
  /** SERVICE listings: minutes per appointment. */
  minutes?: number;
}
interface PackCategory { key: string; name: string; items: PackItem[] }
interface PackStore {
  key: string;
  name: string;
  vendorType: VendorType;
  description: string;
  addressLine1: string;
  /** Degrees from the launch city (Georgetown). */
  offset: { lat: number; lng: number };
  hours: { open: string; close: string };
  cuisineTypes: string[];
  tags: string[];
  /** The pictures' background, "#rrggbb". */
  colour: string;
  categories: PackCategory[];
}

const FICTIONAL = "A fictional store in Swift's App Review demo.";

export const REVIEW_PACK_STORES: readonly PackStore[] = [
  {
    key: 'hibiscus-row-kitchen', name: 'Hibiscus Row Kitchen', vendorType: 'RESTAURANT',
    description: `Home-style Guyanese plates, cooked fresh. ${FICTIONAL}`,
    addressLine1: '14 Hibiscus Row (demo address)', offset: { lat: 0.004, lng: 0.003 },
    hours: { open: '10:00', close: '22:00' }, cuisineTypes: ['Guyanese', 'Caribbean'], tags: ['Lunch', 'Dinner'],
    colour: '#a23b2a',
    categories: [
      { key: 'mains', name: 'Mains', items: [
        { key: 'pepperpot-and-bread', name: 'Pepperpot & Bread', description: 'Slow-cooked beef pepperpot with a soft white loaf.', price: 2200 },
        { key: 'chicken-curry-and-roti', name: 'Chicken Curry & Roti', description: 'Bone-in chicken curry with two dhal puri rotis.', price: 1800 },
        { key: 'cook-up-rice', name: 'Cook-up Rice', description: 'Rice and black-eye peas cooked in coconut milk, with chicken.', price: 1500 },
        { key: 'chicken-chow-mein', name: 'Chicken Chow Mein', description: 'Stir-fried noodles with chicken and vegetables.', price: 1300 },
        { key: 'vegetable-fried-rice', name: 'Vegetable Fried Rice', description: 'Wok-fried rice with mixed vegetables.', price: 1200 },
        { key: 'bake-and-saltfish', name: 'Bake & Saltfish', description: 'Fried bakes with seasoned saltfish.', price: 1000 },
      ] },
      { key: 'drinks', name: 'Drinks', items: [
        { key: 'mauby', name: 'Mauby', description: 'Chilled mauby bark drink, 500 ml.', price: 400 },
        { key: 'sorrel-drink', name: 'Sorrel Drink', description: 'Spiced sorrel, 500 ml.', price: 450 },
        { key: 'lime-swank', name: 'Lime Swank', description: 'Fresh lime juice, lightly sweetened, 500 ml.', price: 350 },
      ] },
    ],
  },
  {
    key: 'cassia-lane-grocer', name: 'Cassia Lane Grocer', vendorType: 'SUPERMARKET',
    description: `Pantry staples and fresh produce. ${FICTIONAL}`,
    addressLine1: '3 Cassia Lane (demo address)', offset: { lat: -0.006, lng: 0.005 },
    hours: { open: '07:00', close: '21:00' }, cuisineTypes: [], tags: ['Groceries', 'Produce'],
    colour: '#2e7d4f',
    categories: [
      { key: 'pantry', name: 'Pantry', items: [
        { key: 'white-rice-2kg', name: 'White Rice 2 kg', description: 'Long-grain white rice.', price: 900, unit: '2 kg' },
        { key: 'brown-sugar-2kg', name: 'Brown Sugar 2 kg', description: 'Local brown sugar.', price: 750, unit: '2 kg' },
        { key: 'flour-2kg', name: 'Flour 2 kg', description: 'All-purpose flour.', price: 700, unit: '2 kg' },
        { key: 'cooking-oil-1l', name: 'Cooking Oil 1 L', description: 'Vegetable cooking oil.', price: 950, unit: '1 L' },
        { key: 'red-beans-1lb', name: 'Red Beans 1 lb', description: 'Dried red kidney beans.', price: 450, unit: '1 lb' },
      ] },
      { key: 'fresh-produce', name: 'Fresh produce', items: [
        { key: 'plantains', name: 'Plantains (4)', description: 'Four ripe plantains.', price: 600, unit: 'bunch' },
        { key: 'tomatoes-1lb', name: 'Tomatoes 1 lb', description: 'Fresh tomatoes.', price: 500, unit: '1 lb' },
        { key: 'bora', name: 'Bora (bunch)', description: 'Fresh bora beans.', price: 300, unit: 'bunch' },
      ] },
      { key: 'dairy-and-eggs', name: 'Dairy & eggs', items: [
        { key: 'eggs-dozen', name: 'Eggs (dozen)', description: 'A dozen large eggs.', price: 1200, unit: 'dozen' },
        { key: 'cheddar-250g', name: 'Cheddar Cheese 250 g', description: 'Mild cheddar.', price: 1100, unit: '250 g' },
      ] },
    ],
  },
  {
    key: 'morning-kite-bakery', name: 'Morning Kite Bakery & Cafe', vendorType: 'RESTAURANT',
    description: `Fresh bread, pastries and coffee. ${FICTIONAL}`,
    addressLine1: '27 Kite Hill Road (demo address)', offset: { lat: 0.008, lng: -0.002 },
    hours: { open: '06:30', close: '19:00' }, cuisineTypes: ['Bakery', 'Cafe'], tags: ['Breakfast', 'Pastries'],
    colour: '#8a5a2b',
    categories: [
      { key: 'bakery', name: 'Bakery', items: [
        { key: 'salara', name: 'Salara Coconut Roll', description: 'Sweet bread rolled with red coconut filling.', price: 700 },
        { key: 'pine-tart', name: 'Pine Tart', description: 'Flaky pastry with pineapple jam.', price: 300 },
        { key: 'cheese-roll', name: 'Cheese Roll', description: 'Buttery pastry with cheese.', price: 250 },
        { key: 'butter-flap', name: 'Butter Flap', description: 'Soft folded butter bread.', price: 250 },
        { key: 'coconut-buns', name: 'Coconut Buns', description: 'Two spiced coconut buns.', price: 200 },
        { key: 'plait-bread', name: 'Plait Bread', description: 'A braided white loaf.', price: 600 },
      ] },
      { key: 'coffee-and-tea', name: 'Coffee & tea', items: [
        { key: 'black-coffee', name: 'Black Coffee', description: 'Hot brewed coffee, 12 oz.', price: 500 },
        { key: 'cafe-latte', name: 'Cafe Latte', description: 'Espresso with steamed milk, 12 oz.', price: 700 },
        { key: 'ginger-tea', name: 'Ginger Tea', description: 'Fresh ginger tea, 12 oz.', price: 400 },
      ] },
    ],
  },
  {
    key: 'lamp-post-care', name: 'Lamp Post Care & Convenience', vendorType: 'STORE',
    description: `Everyday personal care and household basics. ${FICTIONAL}`,
    addressLine1: '8 Lamp Post Lane (demo address)', offset: { lat: -0.003, lng: 0.006 },
    hours: { open: '08:00', close: '22:00' }, cuisineTypes: [], tags: ['Personal care', 'Convenience'],
    colour: '#1f6f8b',
    categories: [
      { key: 'personal-care', name: 'Personal care', items: [
        { key: 'toothpaste', name: 'Toothpaste 100 ml', description: 'Fluoride toothpaste.', price: 600, unit: '100 ml' },
        { key: 'bar-soap', name: 'Bar Soap (3 pack)', description: 'Three mild bath soaps.', price: 450, unit: '3 pack' },
        { key: 'hand-sanitiser', name: 'Hand Sanitiser 250 ml', description: 'Alcohol hand gel.', price: 700, unit: '250 ml' },
        { key: 'sunscreen', name: 'Sunscreen SPF 30', description: 'Broad-spectrum sun lotion, 120 ml.', price: 2500, unit: '120 ml' },
        { key: 'bandages', name: 'Adhesive Bandages (20)', description: 'Box of 20 assorted plasters.', price: 500, unit: 'box' },
      ] },
      { key: 'household', name: 'Household', items: [
        { key: 'paper-towels', name: 'Paper Towels (2 rolls)', description: 'Two absorbent kitchen rolls.', price: 650, unit: '2 rolls' },
        { key: 'bottled-water', name: 'Bottled Water 1.5 L', description: 'Still drinking water.', price: 250, unit: '1.5 L' },
        { key: 'insect-repellent', name: 'Insect Repellent', description: 'Mosquito repellent spray, 150 ml.', price: 1200, unit: '150 ml' },
      ] },
    ],
  },
  {
    key: 'tidewater-barber', name: 'Tidewater Barber & Braids', vendorType: 'SERVICE',
    description: `Cuts, trims and braids by appointment. ${FICTIONAL}`,
    addressLine1: '51 Tidewater Street (demo address)', offset: { lat: 0.002, lng: 0.009 },
    hours: { open: '09:00', close: '18:00' }, cuisineTypes: [], tags: ['Barber', 'Hair'],
    colour: '#5b3f8c',
    categories: [
      { key: 'services', name: 'Services', items: [
        { key: 'mens-haircut', name: "Men's Haircut", description: 'Cut and style, 30 minutes.', price: 2000, minutes: 30 },
        { key: 'beard-trim', name: 'Beard Trim', description: 'Shape and line-up, 15 minutes.', price: 1000, minutes: 15 },
        { key: 'kids-haircut', name: "Kids' Haircut", description: 'For under-12s, 30 minutes.', price: 1500, minutes: 30 },
        { key: 'hot-towel-shave', name: 'Hot Towel Shave', description: 'Classic straight-razor shave, 30 minutes.', price: 1500, minutes: 30 },
        { key: 'cornrows', name: 'Cornrows', description: 'Neat cornrows, about 90 minutes.', price: 3500, minutes: 90 },
        { key: 'box-braids', name: 'Box Braids', description: 'Medium box braids, about 3 hours.', price: 6000, minutes: 180 },
      ] },
    ],
  },
];

// ---------------------------------------------------------------------------
// Deterministic identity
// ---------------------------------------------------------------------------

/** id = rvp_<kind>_<sha256(version, tenant, kind, key)[:24]> — never random. */
export function packId(tenantId: string, kind: string, key: string): string {
  const h = crypto.createHash('sha256').update(`${REVIEW_CONTENT_PACK_VERSION}\0${tenantId}\0${kind}\0${key}`).digest('hex');
  return `rvp_${kind}_${h.slice(0, 24)}`;
}

export function packImageUrl(storeKey: string, itemKey: string): string {
  return `/uploads/items/${REVIEW_PACK_IMAGE_DIR}${storeKey}--${itemKey}.png`;
}

export interface PackPlan {
  ownerUserId: string;
  vendorOwnerId: string;
  vendors: Array<{ id: string; slug: string; store: PackStore }>;
  hours: Array<{ id: string; vendorId: string; dayOfWeek: number; store: PackStore }>;
  categories: Array<{ id: string; vendorId: string; sortOrder: number; category: PackCategory }>;
  items: Array<{ id: string; vendorId: string; categoryId: string; sortOrder: number; item: PackItem; store: PackStore }>;
}

/** Every row the pack owns in `tenantId`, with its id — pure. */
export function planReviewContentPack(tenantId: string): PackPlan {
  const plan: PackPlan = {
    ownerUserId: packId(tenantId, 'usr', 'owner'),
    vendorOwnerId: packId(tenantId, 'own', 'owner'),
    vendors: [], hours: [], categories: [], items: [],
  };
  for (const store of REVIEW_PACK_STORES) {
    const vendorId = packId(tenantId, 'ven', store.key);
    plan.vendors.push({ id: vendorId, slug: `${tenantId}-${store.key}`, store });
    for (let dow = 0; dow < 7; dow++) plan.hours.push({ id: packId(tenantId, 'hrs', `${store.key}:${dow}`), vendorId, dayOfWeek: dow, store });
    store.categories.forEach((category, ci) => {
      const categoryId = packId(tenantId, 'cat', `${store.key}:${category.key}`);
      plan.categories.push({ id: categoryId, vendorId, sortOrder: ci, category });
      category.items.forEach((item, ii) => {
        plan.items.push({ id: packId(tenantId, 'itm', `${store.key}:${item.key}`), vendorId, categoryId, sortOrder: ii, item, store });
      });
    });
  }
  return plan;
}

// ---------------------------------------------------------------------------
// The tenant guard
// ---------------------------------------------------------------------------

export class ReviewTenantRefusedError extends Error {
  constructor(slug: string, why: string) {
    super(`[STA-1] content pack refused for "${slug}": ${why}`);
    this.name = 'ReviewTenantRefusedError';
  }
}

/** The ONLY tenant the pack may touch: an existing, purge-protected REVIEW tenant. */
export async function assertReviewTenant(prisma: PrismaClient, slug: string): Promise<{ id: string }> {
  if (!REVIEW_SLUG_PATTERN.test(slug)) throw new ReviewTenantRefusedError(slug, 'the slug must match /^review-[a-z0-9-]{2,40}$/');
  const tenant = await prisma.tenant.findUnique({ where: { id: slug }, select: { id: true, kind: true, purgeProtected: true } });
  if (!tenant) throw new ReviewTenantRefusedError(slug, 'no such tenant — run review:provision first');
  if (tenant.kind !== 'REVIEW') throw new ReviewTenantRefusedError(slug, `the tenant is ${tenant.kind}, not REVIEW`);
  if (!tenant.purgeProtected) throw new ReviewTenantRefusedError(slug, 'the tenant is not purge-protected');
  return { id: tenant.id };
}

// ---------------------------------------------------------------------------
// The seed
// ---------------------------------------------------------------------------

export type ContentPackState = 'ABSENT' | 'INCOMPLETE' | 'PRESENT';
export interface ContentPackFacts {
  state: ContentPackState;
  expectedStores: number;
  stores: number;
  /** ACTIVE + verified + open + accepting orders: what a reviewer can order from. */
  orderableStores: number;
  expectedItems: number;
  items: number;
  /** The rider and taxi driver logins, and how many would pass the go-online document gate. */
  partners: ReviewPartnerFacts;
}

export interface ContentPackSeedResult extends ContentPackFacts {
  tenantId: string;
  version: string;
  categories: number;
  /** Partner fixture documents committed by this run (0 on an idempotent re-run). */
  partnerDocumentsCommitted: number;
}

/** Pick the synthetic owner's phone: deterministic per tenant, never one already taken. */
async function ownerPhoneFor(prisma: PrismaClient, tenantId: string, ownerUserId: string): Promise<string> {
  const existing = await runWithoutTenant(
    () => prisma.user.findUnique({ where: { id: ownerUserId }, select: { tenantId: true, phone: true } }),
    'review-pack-owner',
  );
  if (existing) {
    if (existing.tenantId !== tenantId) throw new ReviewTenantRefusedError(tenantId, 'the pack owner id already belongs to another tenant');
    return existing.phone;
  }
  const start = parseInt(crypto.createHash('sha256').update(tenantId).digest('hex').slice(0, 4), 16) % 100;
  for (let i = 0; i < 100; i++) {
    const phone = `${PACK_OWNER_PHONE_PREFIX}${String((start + i) % 100).padStart(2, '0')}`;
    const taken = await runWithoutTenant(
      () => prisma.user.findUnique({ where: { phone }, select: { id: true } }),
      'review-pack-owner',
    );
    if (!taken) return phone;
  }
  throw new ReviewTenantRefusedError(tenantId, `every ${PACK_OWNER_PHONE_PREFIX}NN identifier is taken`);
}

/**
 * Seeds (or heals) the pack inside ONE review tenant. Idempotent; refuses any
 * tenant that is not REVIEW before the first write; never deletes.
 */
export async function seedReviewContentPack(prisma: PrismaClient, input: { slug: string }): Promise<ContentPackSeedResult> {
  const { id: tenantId } = await assertReviewTenant(prisma, input.slug);
  const plan = planReviewContentPack(tenantId);
  const ownerPhone = await ownerPhoneFor(prisma, tenantId, plan.ownerUserId);
  let partnerDocumentsCommitted = 0;

  await runWithTenant(tenantId, async () => {
    await prisma.user.upsert({
      where: { id: plan.ownerUserId, tenantId },
      create: {
        id: plan.ownerUserId, tenantId, phone: ownerPhone, firstName: 'Demo', lastName: 'Store Owner',
        roles: ['VENDOR_OWNER'], activeRole: 'VENDOR_OWNER', isSynthetic: true,
      },
      update: { firstName: 'Demo', lastName: 'Store Owner' },
    });
    await prisma.vendorOwner.upsert({
      where: { userId: plan.ownerUserId },
      create: { id: plan.vendorOwnerId, userId: plan.ownerUserId },
      update: {},
    });

    for (const { id, slug, store } of plan.vendors) {
      const place = {
        name: store.name, description: store.description, vendorType: store.vendorType,
        addressLine1: store.addressLine1, city: 'Georgetown', region: 'Demerara-Mahaica',
        latitude: LAUNCH_CITY.lat + store.offset.lat, longitude: LAUNCH_CITY.lng + store.offset.lng,
        cuisineTypes: store.cuisineTypes, tags: store.tags,
      };
      // Live inside the fiction, and only there; no MMG link, no public phone.
      const live = {
        status: 'ACTIVE' as const, isVerified: true, acceptingOrders: true, isCurrentlyOpen: true,
        mmgPayUrl: null, mmgPayUrlPending: null, mmgPayUrlPendingAt: null, mmgPayUrlApplyAt: null, publicPhone: null,
      };
      await prisma.vendor.upsert({
        where: { id, tenantId },
        create: { id, tenantId, slug, ownerId: plan.vendorOwnerId, phone: ownerPhone, isSynthetic: true, ...place, ...live },
        update: { ...place, ...live },
      });
    }

    for (const h of plan.hours) {
      await prisma.operatingHours.upsert({
        where: { id: h.id, vendorId: h.vendorId },
        create: { id: h.id, vendorId: h.vendorId, dayOfWeek: h.dayOfWeek, openTime: h.store.hours.open, closeTime: h.store.hours.close, isClosed: false },
        update: { openTime: h.store.hours.open, closeTime: h.store.hours.close, isClosed: false },
      });
    }

    for (const c of plan.categories) {
      await prisma.category.upsert({
        where: { id: c.id, tenantId },
        create: { id: c.id, tenantId, vendorId: c.vendorId, name: c.category.name, sortOrder: c.sortOrder, isActive: true },
        update: { name: c.category.name, sortOrder: c.sortOrder, isActive: true },
      });
    }

    for (const it of plan.items) {
      const service = it.store.vendorType === 'SERVICE';
      const fulfillment: FulfillmentType = service ? 'APPOINTMENT' : 'DELIVERY';
      const bookingConfig: Prisma.InputJsonValue | undefined = service
        ? {
          durationMinutes: it.item.minutes ?? 30,
          slots: Array.from({ length: 7 }, (_, dayOfWeek) => ({ dayOfWeek, start: '09:00', end: '17:00' })),
          serviceMode: 'AT_BUSINESS',
        }
        : undefined;
      // Stock is never written here (inventory/stock.ts is its one writer):
      // pack items are created untracked (stockQuantity null = always in stock).
      const fields = {
        name: it.item.name, description: it.item.description, imageUrl: packImageUrl(it.store.key, it.item.key),
        basePrice: it.item.price, fulfillment, unit: it.item.unit ?? null, sortOrder: it.sortOrder,
        isAvailable: true,
        ...(bookingConfig ? { bookingConfig } : {}),
      };
      await prisma.item.upsert({
        where: { id: it.id, tenantId },
        create: { id: it.id, tenantId, vendorId: it.vendorId, categoryId: it.categoryId, dietaryTags: [], allergens: [], ...fields },
        update: fields,
      });
    }

    // The fiction's rider and taxi driver: verified partners, inside this tenant only.
    partnerDocumentsCommitted = (await seedReviewPartners(prisma, tenantId)).documentsCommitted;
  });

  const facts = await reviewContentPackFacts(prisma, tenantId);
  return { tenantId, version: REVIEW_CONTENT_PACK_VERSION, categories: plan.categories.length, partnerDocumentsCommitted, ...facts };
}

/** At least one rider and one taxi driver login, every one of them able to go online. */
export function partnersComplete(p: ReviewPartnerFacts): boolean {
  return p.RIDER.credentials > 0 && p.DRIVER.credentials > 0
    && p.RIDER.ready === p.RIDER.credentials && p.DRIVER.ready === p.DRIVER.credentials;
}

/** What of the pack exists in `tenantId` — counted by the pack's own ids only. */
export async function reviewContentPackFacts(prisma: PrismaClient, tenantId: string): Promise<ContentPackFacts> {
  const plan = planReviewContentPack(tenantId);
  const [vendors, items, partners] = await Promise.all([
    prisma.vendor.findMany({
      where: { tenantId, id: { in: plan.vendors.map((v) => v.id) } },
      select: { status: true, isVerified: true, acceptingOrders: true, isCurrentlyOpen: true },
    }),
    prisma.item.count({ where: { tenantId, id: { in: plan.items.map((i) => i.id) }, isAvailable: true } }),
    reviewPartnerFacts(prisma, tenantId),
  ]);
  const orderableStores = vendors.filter((v) => v.status === 'ACTIVE' && v.isVerified && v.acceptingOrders && v.isCurrentlyOpen).length;
  const expectedStores = plan.vendors.length;
  const expectedItems = plan.items.length;
  const storesComplete = vendors.length === expectedStores && orderableStores === expectedStores && items === expectedItems;
  const state: ContentPackState = vendors.length === 0 && items === 0 && partners.profiles === 0
    ? 'ABSENT'
    : storesComplete && partnersComplete(partners) ? 'PRESENT' : 'INCOMPLETE';
  return { state, expectedStores, stores: vendors.length, orderableStores, expectedItems, items, partners };
}

// ---------------------------------------------------------------------------
// The pictures
// ---------------------------------------------------------------------------

const PICTURE = /^([a-z0-9-]{1,48})--([a-z0-9-]{1,48})\.png$/;
const pictureCache = new Map<string, Buffer>();

/**
 * The PNG for `<store>--<item>.png` under REVIEW_PACK_IMAGE_DIR, or null when
 * the pack declares no such picture. Bounded: at most one cached buffer per
 * item the pack declares.
 */
export function reviewPackPicture(file: string): Buffer | null {
  const m = PICTURE.exec(file);
  if (!m) return null;
  const cached = pictureCache.get(file);
  if (cached) return cached;
  const store = REVIEW_PACK_STORES.find((s) => s.key === m[1]);
  const item = store?.categories.flatMap((c) => c.items).find((i) => i.key === m[2]);
  if (!store || !item || !isLetterable(item.name) || !isLetterable(store.name)) return null;
  const png = renderPackPicture({ title: item.name, caption: store.name, background: store.colour });
  pictureCache.set(file, png);
  return png;
}
